# Generated by Django 2.2.4 on 2020-05-24 08:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiftuser',
            name='profile_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=users.models.user_profile_picture_dir),
        ),
    ]
