# Generated by Django 2.2.4 on 2020-05-24 08:52

from django.db import migrations, models
import wishes.models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=wishes.models.wishes_image_dir),
        ),
    ]
